USE WAREHOUSE SUPERSTORE_WH;

CREATE DATABASE IF NOT EXISTS SUPERSTORE_DB;

CREATE SCHEMA IF NOT EXISTS SUPERSTORE_DB.RAW;
CREATE SCHEMA IF NOT EXISTS SUPERSTORE_DB.CLEAN;
CREATE SCHEMA IF NOT EXISTS SUPERSTORE_DB.ANALYTICS;