CREATE OR REPLACE TABLE SUPERSTORE_DB.RAW.SUPERSTORE_RAW (
    ROW_ID INTEGER,
    ORDER_ID VARCHAR(50),
    ORDER_DATE VARCHAR(20),
    SHIP_DATE VARCHAR(20),
    SHIP_MODE VARCHAR(50),
    CUSTOMER_ID VARCHAR(50),
    CUSTOMER_NAME VARCHAR(200),
    SEGMENT VARCHAR(50),
    COUNTRY VARCHAR(100),
    CITY VARCHAR(100),
    STATE VARCHAR(100),
    POSTAL_CODE FLOAT,
    REGION VARCHAR(50),
    PRODUCT_ID VARCHAR(50),
    CATEGORY VARCHAR(100),
    SUB_CATEGORY VARCHAR(100),
    PRODUCT_NAME VARCHAR(500),
    SALES FLOAT
);

CREATE OR REPLACE FILE FORMAT SUPERSTORE_DB.RAW.SUPERSTORE_CSV_FORMAT
TYPE = 'CSV'
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
SKIP_HEADER = 1
NULL_IF = ('NULL', 'null', '');

CREATE OR REPLACE STAGE SUPERSTORE_DB.RAW.SUPERSTORE_STAGE
FILE_FORMAT = SUPERSTORE_DB.RAW.SUPERSTORE_CSV_FORMAT;