LIST @SUPERSTORE_DB.RAW.SUPERSTORE_STAGE;

COPY INTO SUPERSTORE_DB.RAW.SUPERSTORE_RAW
FROM @SUPERSTORE_DB.RAW.SUPERSTORE_STAGE
FILE_FORMAT = SUPERSTORE_DB.RAW.SUPERSTORE_CSV_FORMAT
ON_ERROR = 'ABORT_STATEMENT';

SELECT COUNT(*) AS ROW_COUNT
FROM SUPERSTORE_DB.RAW.SUPERSTORE_RAW;

SELECT *
FROM SUPERSTORE_DB.RAW.SUPERSTORE_RAW
LIMIT 10;