CREATE OR REPLACE TABLE SUPERSTORE_DB.CLEAN.SUPERSTORE AS
SELECT
    ROW_ID,
    ORDER_ID,
    TO_DATE(ORDER_DATE, 'DD/MM/YYYY') AS ORDER_DATE,
    TO_DATE(SHIP_DATE, 'DD/MM/YYYY') AS SHIP_DATE,
    SHIP_MODE,
    CUSTOMER_ID,
    CUSTOMER_NAME,
    SEGMENT,
    COUNTRY,
    CITY,
    STATE,
    POSTAL_CODE,
    REGION,
    PRODUCT_ID,
    CATEGORY,
    SUB_CATEGORY,
    PRODUCT_NAME,
    SALES,
    DATEDIFF(
        'day',
        TO_DATE(ORDER_DATE, 'DD/MM/YYYY'),
        TO_DATE(SHIP_DATE, 'DD/MM/YYYY')
    ) AS SHIPPING_DAYS
FROM SUPERSTORE_DB.RAW.SUPERSTORE_RAW;